#!/usr/bin/env python3
"""
Morning Brief Generator
Calls Claude API with web search → generates HTML brief → pushes to GitHub → sends Gmail draft
Runs via GitHub Actions at 7:00 AM ART (10:00 UTC) on weekdays
"""

import os
import sys
import json
import base64
import subprocess
import datetime
import anthropic
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

# ── Config ──────────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY   = os.environ["ANTHROPIC_API_KEY"]
GMAIL_USER          = os.environ.get("GMAIL_USER", "marciofabrizio@gmail.com")
GMAIL_APP_PASSWORD  = os.environ.get("GMAIL_APP_PASSWORD", "")
RECIPIENT_EMAIL     = os.environ.get("RECIPIENT_EMAIL", "marciofabrizio@gmail.com")
GITHUB_TOKEN        = os.environ.get("GITHUB_TOKEN", "")   # injected by Actions automatically
REPO_DIR            = Path(__file__).parent.resolve()

# ── Prompt ───────────────────────────────────────────────────────────────────
CONTEXT_MD = (REPO_DIR / "CONTEXT.md").read_text()

def build_prompt(today: str, weekday: str, war_day: int) -> str:
    return f"""You are generating the Morning Brief for {weekday}, {today} (War Day {war_day}).

Read CONTEXT.md carefully — it defines EVERYTHING: coverage areas, portfolio, CSS design system, HTML structure, tone, and style rules.

CONTEXT.md:
---
{CONTEXT_MD}
---

INSTRUCTIONS:
1. Run web searches for today's data across all 5 coverage areas (geopolitics, markets, Argentina, Brazil, SAP/regulation). Use today's date "{today}" in every query.
2. Generate a complete, self-contained HTML brief following the EXACT structure and CSS from CONTEXT.md.
3. Use the correct header gradient for today's market tone.
4. Include all sections in order: Overview alerts → Action Items → Geopolitics → Portfolio → Markets → Regulation → SAP → Week Ahead → footer.
5. Update scenario probabilities based on latest news.
6. Cite all facts inline with <a href="URL">source</a> links.
7. Footer: "Generated by Claude · {weekday} {today} · 7:00 AM ART · War Day {war_day}"

Output ONLY the complete HTML. No markdown fences. No explanation. Start with <!DOCTYPE html>."""


def get_war_day() -> int:
    """War started Feb 28 2026 = Day 1."""
    war_start = datetime.date(2026, 2, 28)
    today = datetime.date.today()
    return max(1, (today - war_start).days + 1)


# ── Claude API call ───────────────────────────────────────────────────────────
def generate_brief(today_str: str, weekday: str, war_day: int) -> str:
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    print(f"[brief] Calling Claude API for {today_str} (War Day {war_day})...")

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=16000,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{
            "role": "user",
            "content": build_prompt(today_str, weekday, war_day)
        }]
    )

    # Extract the final text block (HTML)
    html = ""
    for block in response.content:
        if block.type == "text":
            html += block.text

    if not html.strip().startswith("<!DOCTYPE"):
        # Sometimes Claude wraps in backticks — strip them
        import re
        match = re.search(r'<!DOCTYPE html>.*', html, re.DOTALL | re.IGNORECASE)
        if match:
            html = match.group(0)
            # Remove trailing ``` if present
            html = re.sub(r'```\s*$', '', html).strip()

    if not html.strip().startswith("<!DOCTYPE"):
        raise ValueError(f"Claude did not return valid HTML. Got: {html[:200]}")

    print(f"[brief] HTML generated — {len(html):,} chars")
    return html


# ── File operations ───────────────────────────────────────────────────────────
def save_brief(html: str, date_str: str) -> Path:
    briefs_dir = REPO_DIR / "briefs"
    briefs_dir.mkdir(exist_ok=True)

    brief_path = briefs_dir / f"{date_str}.html"
    brief_path.write_text(html, encoding="utf-8")
    print(f"[file] Saved {brief_path}")

    index_path = REPO_DIR / "index.html"
    index_path.write_text(html, encoding="utf-8")
    print(f"[file] Updated index.html")

    return brief_path


def update_archive(date_str: str, headline: str):
    """Insert new brief row at the top of the current month section in archive.html."""
    archive_path = REPO_DIR / "archive.html"
    if not archive_path.exists():
        print("[archive] archive.html not found — skipping")
        return

    content = archive_path.read_text(encoding="utf-8")

    # Format date for display
    dt = datetime.datetime.strptime(date_str, "%Y-%m-%d")
    month_label = dt.strftime("%B %Y")  # e.g. "March 2026"
    day_label   = dt.strftime("%b %-d") # e.g. "Mar 25"

    new_row = f'''  <a class="brief-row" href="briefs/{date_str}.html">
    <span class="brief-date">{day_label}</span>
    <span class="brief-headline">{headline}</span>
    <span class="badge b-normal">WAR DAY {get_war_day()}</span>
  </a>'''

    # Insert after the month div if it exists, otherwise after <div class="wrap">
    month_marker = f'<div class="month">{month_label}</div>'
    if month_marker in content:
        content = content.replace(
            month_marker,
            month_marker + "\n\n" + new_row
        )
    else:
        # Add new month section at the top
        wrap_marker = '<div class="wrap">'
        new_month_section = f'''{wrap_marker}
  <h1>📊 Morning Brief — Archive</h1>
  <div class="sub">Daily intelligence briefing · <a href="index.html" style="color:#2563eb;font-weight:600">→ Latest Brief</a></div>

  <div class="month">{month_label}</div>

{new_row}'''
        content = content.replace(wrap_marker, new_month_section, 1)

    archive_path.write_text(content, encoding="utf-8")
    print(f"[archive] Updated archive.html with {date_str}")


# ── Git push ──────────────────────────────────────────────────────────────────
def git_push(date_str: str, headline: str):
    """Commit and push — token is injected via GITHUB_TOKEN env in Actions."""
    if GITHUB_TOKEN:
        subprocess.run(
            ["git", "remote", "set-url", "origin",
             f"https://x-access-token:{GITHUB_TOKEN}@github.com/marcioherlein/morning.git"],
            cwd=REPO_DIR, check=True
        )

    subprocess.run(["git", "config", "user.email", "bot@morning-brief"], cwd=REPO_DIR, check=True)
    subprocess.run(["git", "config", "user.name", "Morning Brief Bot"], cwd=REPO_DIR, check=True)
    subprocess.run(["git", "add", "."], cwd=REPO_DIR, check=True)

    commit_msg = f"Brief {date_str} · {headline}"
    result = subprocess.run(
        ["git", "diff", "--staged", "--quiet"],
        cwd=REPO_DIR
    )
    if result.returncode == 0:
        print("[git] Nothing to commit — brief already up to date")
        return

    subprocess.run(["git", "commit", "-m", commit_msg], cwd=REPO_DIR, check=True)
    subprocess.run(["git", "push", "origin", "main"], cwd=REPO_DIR, check=True)
    print(f"[git] Pushed: {commit_msg}")

    # Strip token from remote URL after push
    subprocess.run(
        ["git", "remote", "set-url", "origin",
         "https://github.com/marcioherlein/morning.git"],
        cwd=REPO_DIR, check=True
    )


# ── Gmail ─────────────────────────────────────────────────────────────────────
def send_gmail_draft(html: str, date_str: str, headline: str):
    if not GMAIL_APP_PASSWORD:
        print("[email] GMAIL_APP_PASSWORD not set — skipping email")
        return

    dt = datetime.datetime.strptime(date_str, "%Y-%m-%d")
    date_display = dt.strftime("%-d %b %Y")    # e.g. "25 Mar 2026"
    weekday      = dt.strftime("%A")            # e.g. "Wednesday"
    subject      = f"☀️ Morning Brief · {date_display} · {headline}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = GMAIL_USER
    msg["To"]      = RECIPIENT_EMAIL
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_USER, RECIPIENT_EMAIL, msg.as_string())
        print(f"[email] Sent to {RECIPIENT_EMAIL}: {subject}")
    except Exception as e:
        print(f"[email] Failed: {e}")


# ── Headline extraction ───────────────────────────────────────────────────────
def extract_headline(html: str) -> str:
    """Pull the hdr-sub paragraph first sentence as a one-liner."""
    import re
    # Try to get the first badge texts
    badges = re.findall(r'class="badge[^"]*">([^<]+)<', html)
    if badges:
        return " · ".join(b.strip() for b in badges[:3])
    # Fallback: first sentence of hdr-sub
    match = re.search(r'class="hdr-sub"[^>]*>(.*?)</div>', html, re.DOTALL)
    if match:
        text = re.sub(r'<[^>]+>', '', match.group(1)).strip()
        return text[:80].split(".")[0].strip()
    return "Daily Intelligence Briefing"


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    today = datetime.date.today()
    date_str = today.strftime("%Y-%m-%d")
    weekday  = today.strftime("%A")
    war_day  = get_war_day()

    # Skip weekends
    if today.weekday() >= 5:
        print(f"[brief] {weekday} — skipping (weekend)")
        sys.exit(0)

    print(f"[brief] Starting — {weekday} {date_str} · War Day {war_day}")

    html = generate_brief(date_str, weekday, war_day)
    headline = extract_headline(html)
    print(f"[brief] Headline: {headline}")

    save_brief(html, date_str)
    update_archive(date_str, headline)
    git_push(date_str, headline)
    send_gmail_draft(html, date_str, headline)

    print(f"[brief] Done ✓ — {date_str}")


if __name__ == "__main__":
    main()
